### ISSUE TITLE
增加对Win10的支持

### ISSUE THREAD

**Issue by RainEggplant** [zjccsg/permo#3]
Win10下运行提示驱动加载失败，应该是win10不兼容winpcap所致。

**Comment by ted423** [comment]
win 10 1803可以运行，估计是加驱时被杀软干掉了

**Comment by aa12356jm** [comment]
@ted423 你好，请问在win10    x64可以编译通过吗？我这里一直提示不支持asm，因为代码里面有汇编，所以一直编译不过，可否共享一下代码，谢谢

**Comment by ted423** [comment]
@aa12356jm 我没编译呃，只是下载的release的在用的

**Comment by zjccsg** [comment]
@aa12356jm 我之前在win7下，vs2008编译是OK的，没在win10环境下编译过。git上代码是全的。

**Comment by aa12356jm** [comment]
@zjccsg 好的，谢谢
